// Generated by CoffeeScript 1.9.3
(function() {
  var Pattern, PatternSet;

  Pattern = require("./pattern");

  PatternSet = (function() {
    function PatternSet() {
      this._patterns = {};
    }

    PatternSet.prototype.add = function(specification) {
      var base;
      return (base = this._patterns)[specification] != null ? base[specification] : base[specification] = new Pattern(specification);
    };

    PatternSet.prototype.remove = function(specification) {
      return delete this._patterns[specification];
    };

    PatternSet.prototype.match = function(target, callback) {
      var pattern, ref, results, specification;
      results = [];
      ref = this._patterns;
      for (specification in ref) {
        pattern = ref[specification];
        if (pattern.match(target)) {
          if (callback != null) {
            callback(specification);
          }
          results.push(specification);
        }
      }
      return results;
    };

    return PatternSet;

  })();

  module.exports = PatternSet;

}).call(this);
